


# 定义name-server地址
spring:
  rocketmq:
    name-server: 192.168.120.108:9876
    topic: topic-0514
    producer:
      group: group-0514
  application:
    name: rocketmq-provider

server:
  port: 7070


## 定义发布者组名
#  spring.rocketmq.producer.group=group-0827
#  # 定义要发送的topic
#  spring.rocketmq.topic=topic-0827
#  #应用端口
#  server.port=8788
#  #应用名称
#  spring.application.name=springboot-rocketmq-producer
