spring:
  rocketmq:
    name-server: 192.168.120.108:9876
    topic: topic-0514
    consumer:
      group: consumer
  application:
    name: rocketmq-consumer

server:
  port: 7090
# 定义name-server地址
#  spring.rocketmq.name-server=192.168.120.108:9876
#  # 定义消费者组名
#  spring.rocketmq.consumer.group=consumer
#  # 定义要发送的topic
#  spring.rocketmq.topic=topic-0827
#  #应用端口
#  server.port=8789
#  #应用名称
#  spring.application.name=springboot-rocketmq-consumer

